### ISSUE TITLE
Keys should not be in public

### ISSUE THREAD

**Issue by WhiteVoidia** [friej715/tarotbot#1]
Hey! I just noticed that you seem to have the secret keys for this twitter account [in public](https://github.com/friej715/tarotbot/blob/public/keys.js). Just wanted to make sure you were aware of this in case someone else finds those keys and gains access to your twitter bot.

**Comment by friej715** [comment]
Argh, I could have sworn I put those keys in the gitignore! Smh. Thanks very much for the heads up! Am a bit swamped so I'll probably just delete the repo for now til I fix it.
